### ISSUE TITLE
v-facade doesn't work with Vuetify

### ISSUE THREAD

**Issue by gatkinsNZ** [RonaldJerez/vue-input-facade#10]
I switched from vue-the-mask to your library, however it doesn't work correctly with Vuetify's v-text-field. I appreciate you may not officially support Vuetify, but thought I would let you know.

**The Issue:**
If you update the model data value binded to v-text-field then sometimes the v-text-field will not be updated. This only occurs when using the v-facade directive.

I tried to do a codepen example, but couldn't work out how to import your library, but is easily reproducible with something like the below, which results in the input only updating on every second try.
```
<template>
    <div>
        <v-text-field v-model="containerNumber" label="Container #" v-facade="'XXXXXXXXXXXX'"></v-text-field>
        <v-btn @click="update">Update</v-btn>
    </div>
</template>

export default {
    name: 'home',
    data () {
        return {
            containerNumber: 'YYY'
        }
    },
    methods: {  
        update() {
            this.containerNumber = this.containerNumber + 'Z'; 
        }
    },
}
```

**Comment by gogangipark** [comment]
I also want to use v-facade with vuetify.

If you have ant time to help me out, please support vuetify 2.x.

**Comment by RonaldJerez** [comment]
I haven't used vuetify in a project for a while but I'll take a look.  I just checked with a regular input field on the demo page and the directive and the v-model is been updated properly.

**Comment by RonaldJerez** [comment]
I am closing this issue and we can continue the conversation in #11 as they are duplicates.
