### ISSUE TITLE
No type declaration

### ISSUE THREAD

**Issue by douglasg14b** [RonaldJerez/vue-input-facade#13]
As the title says, there i no type declaration fr this, which requires a shim in TypeScript projects.

Otherwise it just throws 

> Could not find a declaration file for module 'vue-input-facade'.

**Comment by RonaldJerez** [comment]
I don’t use type script, but you’re welcome to add type support and open a PR.

**Comment by RonaldJerez** [comment]
Closing as there is not activity here.
