### ISSUE TITLE
Documentation note regarding Vuetify

### ISSUE THREAD

**Issue by ktiedt** [RonaldJerez/vue-input-facade#14]
In order for the `v-facade` directive to work with Vuetify you have to call the `Vue.use(InputFacade);` after Vuetify plugin is loaded.

Hope this helps someone else until Vuetify integrates masking (or your handy plugin) again!

**Comment by ktiedt** [comment]
Although, i cannot seem to access the unmasked value... even using the `event = $event` example

**Comment by RonaldJerez** [comment]
Yea it was mentioned in another issue, seems as vuetify is not sending the event as 2nd param. You’ll need to use “@input.native” to be able to access the event param.  I’m looking to see if there is any other intuitive way to send the unmasked value with vuetify.

**Comment by ktiedt** [comment]
Ahh thank you, I will give that a try. I only noticed the 2 duplicate issues when I searched, but I didnt perhaps read every comment. Definitely appreciate you filling this missing gap in Vue/Vuetify
