### ISSUE TITLE
Delete of masked spaces in webkit Edge and IE11 not possible

### ISSUE THREAD

**Issue by lyssar** [RonaldJerez/vue-input-facade#19]
Hey,
me and my team found an issue using input-facade in Edge.
You can't delete a space character if your mask has spaces in it. 

Example Mask: `DE## #### #### #### #### ##`

You can also reproduce this behaviour with your own demo page on Edge:
https://ronaldjerez.github.io/vue-input-facade/
We tried the one in `Basic Usage` Section on this page. Try to delete the 4 last digits and the spaces with the dash by using only backspace, you will not be able delete the spaces but normal characters.

Kind Regards

**Comment by RonaldJerez** [comment]
I just tried it on webkit Edge (version 80) and its working fine.  I did however see an issue on edge 18, is that the version you are having the problem in?  I will take a look to see what the problem is,  in the meantime a work around is to set the `short` flag.

**Comment by cefuroX** [comment]
Hi,
well yes its Edge in Version 18. We kind of disable the flag at the moment for Edge so our users can use the site.
Thanks for you effort.

**Comment by RonaldJerez** [comment]
I spent some time looking into this, for some reason on Edge am not able to get the selectionEnd to figure out where the cursor needs to be.  I looked back and it seemed to start after version 1.0.4, however the changes there had nothing to do with the directive, so I’m a little stump, and debugging edge is not the greatest but I’ll keep looking into it as time permits

**Comment by RonaldJerez** [comment]
I believe I found the root cause of this issue.  However fixing it causes another issue on edge with the cursor not been updated correctly.  So I'm still looking into a solution that addresses both issues.

**Comment by cefuroX** [comment]
Okay. Thank you for the update on this :)

**Comment by RonaldJerez** [comment]
Unfortunately I was not able to fully fix this for edge classic without introducing additional issues for other browsers. Given that Microsoft has stopped supporting edge classic I’m going to do the same.
