### ISSUE TITLE
incorrectly triggers validation

### ISSUE THREAD

**Issue by pancake-boy** [RonaldJerez/vue-input-facade#21]
**Describe the bug**
I'm migration from vue-the-mask
I'm using a vuetify v-text-field

with vue-the-mask, when the page loads, no validation is triggered.
with vue-input-facade, when the page loads, it seems to set the field to empty string and triggers validation.

it seems the text box is initially null, but the directive sets it to '' empty string data, it triggers an input change

is there a way to force it to remain null?

```
 <v-text-field
      v-model="data"
      v-facade="mask"
      :rules="rules.required"
    >
```

**Comment by RonaldJerez** [comment]
There is no current way to force it to remain null. Since the masked value always goes to an input field it needs to be a string.

Can you just set the initial value to “”? That is still considered falsy if you need to check that a value was set.

**Comment by pancake-boy** [comment]
my model properties defaults to null.
I would have to do some ugly work around to have another variable set to '' and then synchronise that with my model property.

**Comment by RonaldJerez** [comment]
I think i got a solution. Just need to test it out and make sure it doesn't break anything else.

**Comment by ktiedt** [comment]
> my model properties defaults to null.
> I would have to do some ugly work around to have another variable set to '' and then synchronise that with my model property.

Is '' a valid value for your models? Otherwise it seems like a strange thing to avoid...
