### ISSUE TITLE
[IE] Bug with the cursor with facade directive and mask with / delimiter

### ISSUE THREAD

**Issue by DamienRenaud** [RonaldJerez/vue-input-facade#26]
Hello !

Thanks for reading this issue ! I hope the description is clear enough, do not hesitate if you need more information !

**Describe the bug**

Bug version : 1.3.2
It seems there is a bug with the cursor on IE when we use masks with a character as delimiter (eg: the "/" for a date ##/##/####).
The bug appears when using v-facade directive but works fine with component.

I tried to downgrade the version and it seems 1.2.0 works well !

**To Reproduce**

- I created a simple VueJS app with vue-cli

- Add vue-input-facade and import it as global
```typescript
import InputFacade from 'vue-input-facade';
Vue.use(InputFacade);
```

- Add custom-event-polyfill and import it in main.ts file (used for IE)
```import 'custom-event-polyfill';```

- Add 2 inputs, one using facade directive and another with component
```typescript
<h3>Test vue-input-facade</h3>
<input v-facade="'##/##/##'" type="text" />
<br>
<br>
<input-facade mask="##/##/##" type="text" />
```

**Expected behavior**
The cursor should follow the user's input when he is writing

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser : IE
 - Version 11

**Additional context**

Component and directive have different behaviours when deleting input. The directive deletes automatically the "/" but the component doesn't.

Thanks !

**Comment by RonaldJerez** [comment]
Hi, thanks for the report.  We don’t support IE, however this does sound like the same issue as #19. Which I do have a fix for but it causes additional issues so I’m trying to work those out as well.
