### ISSUE TITLE
An question about :masked prop

### ISSUE THREAD

**Issue by iWatchYouFromAfar** [RonaldJerez/vue-input-facade#28]
First of all, thanks for the great plugin!

**Describe the bug**
I'm not sure if this is a bug - I would like to receive the raw format of the phone after submitting the form. But somehow it doesn't work ...

**To Reproduce**
Here is my input:

```
<input
  id="phone"
  v-facade="'+7 (###) ###-##-##'"
  :masked="masked"
  type="tel"
  name="phone"
  placeholder="+7 (___) ___−__−__"
>
```

Here i am defining parameter masked

```
data() {
  return {
    input: '',
    masked: false,
  };
},
```

I also tried to work with props:

```
  props: {
    masked: {
      type: Boolean,
      default: false,
    },
  },
```

But when submitting the form - I get the data after processing the mask:

![gh](https://user-images.githubusercontent.com/16403917/98845887-63376580-245f-11eb-9720-bd322889711f.jpg)

Tell me please - is this a bug or am I doing something wrong?

Thanks!

**Comment by RonaldJerez** [comment]
Hello, it’s not a bug.  You are using the directive which you can’t pass properties to.  You would need to use the component version ‘<input-facade>’ then pass the property to that component.   If you do need to use the directive version you would have to listen to the input event and get the unmasked value that way.  Checkout the demo page, there’s a few usage of both of these scenarios there.

**Comment by iWatchYouFromAfar** [comment]
Thanks for fast and clear answer!
