### ISSUE TITLE
Directive v-facade clearing value from first index of repeated fields

### ISSUE THREAD

**Issue by vicenterusso** [RonaldJerez/vue-input-facade#31]
**Describe the bug**
I'm using [vue-formulate](https://vueformulate.com) to build forms. The mask doesnt works only on the first index. If v-facade is removed, everything works

**To Reproduce**
https://codesandbox.io/s/pybjv?file=/src/App.vue

**Expected behavior**
v-facade directive should works on every form field

**Comment by RonaldJerez** [comment]
The directive attaches it self to the first input found when used in an outer container.  I am not familiar with vue-formulate but looking at your code sample looks like they do some internal work to make the input “repeatable”.  So I don’t think vue-input-facade is compatible with vue-formulate.
