### ISSUE TITLE
"This dependency was not found" on 1.3.5

### ISSUE THREAD

**Issue by i-defranca** [RonaldJerez/vue-input-facade#38]
After updating to 1.3.5, I get "This dependency was not found" on nuxt dev build.

1. Update to 1.3.5
2. Try run dev build

**Expected behavior**
No breaking change from 1.3.4

Edit: setting "vue-input-facade": "1.3.4" on package.json fix the build.

**Comment by RonaldJerez** [comment]
Thanks, I just switched over to GitHub Actions from travisCI, will take a look see what went wrong.

**Comment by RonaldJerez** [comment]
@i-defranca  it has beeb fixed.  Use 1.3.6, I will deprecate 1.3.5
