### ISSUE TITLE
Pre-project question RE IP address masking

### ISSUE THREAD

**Issue by RickKukiela** [RonaldJerez/vue-input-facade#4]
I have an upcoming project where I'm going to need to mask vuetify text field inputs for IP addresses. I need to allow {0-255}.{0-255}.{0-255}.{0-255} so not only do I want to limit the number amount for each value to 255 (ie 256 not valid) and also I want them to be able to enter 8.8.8.8 (one number per octet) without having to do 008.008.008.008 by using a generic mask like ###.###.###.### would required - Is this going to be possible with this library?

**Comment by RonaldJerez** [comment]
I don’t think you can accomplish that with the current implementation.  I have a pipe feature in the beta branch that allows you to manually format the output. You can give that a try, I posted some sample code on issue #1
