### ISSUE TITLE
Does not work with Vuetify inputs, masking breaks

### ISSUE THREAD

**Issue by douglasg14b** [RonaldJerez/vue-input-facade#42]
**Describe the bug**

With vuetify inputs, following thedocs:

```html
          <v-text-field
            :value="model.phone"
            @input.native="model.phone = $event.target.unmaskedValue"
            v-facade="`(###) ###-####`"
            label="Phone number"
            filled>
          </v-text-field>
```

With input: `1234567890` is displays `1234567890` with no masking. It only masks when another number is typed at the end. So input `12345678901` displays `(123) 456-7890` , and then immediately unmasks when the input is no longer focused.

The result of this is that the input is no longer masked.

**Comment by douglasg14b** [comment]
Really, setting the value external to the input causes the masking to be completely borked. You can type in numbers, and they don't show up...etc

**Comment by RonaldJerez** [comment]
I don’t expect that to work.  You are trying to use a directive whose role
is to display formatted text to display non formatted text if I’m looking
at your code correctly. “On input, set the value of the input to the
unformatted value”.

What you are trying to do requires a bit more logic than you may be able to
do with just a few props. You can see the code for the component, that is
already implementing this feature.

**Comment by douglasg14b** [comment]
> I don’t expect that to work.  You are trying to use a directive whose role
is to display formatted text to display non formatted text if I’m looking

When a user is typing into a masked input, is that not unformatted text they are typing? Or when the component loads with an unformatted phone number? Or when an input value is modified else wear? ...etc

It seems odd that "one way data binding" would be officially unsupported. 🤔 

This issue isn't necessarily as you interpreted though: `On input, set the value of the input to the
unformatted value`... That ignores that we're dealing with events & props in the first place. An input event is emitted, we do a thing, and then set a prop. This would be the same as a user typing or pasting those same characters somewhere no?

It's instead `When the value prop is set, format the input`. This example just ties the two together in one spot, but the same behavior can be seen by just having two input components side-by side, one masked, the other not, and typing into the unmasked one. Or by having a process that changes a form field value that is tied to a masked input.

<hr>

I have a component that wraps this and does essentially the same thing as yours:

```
  watch: {
    value (newVal) {
      if (this.unmaskedValue !== newVal) {
        this.maskedValue = newVal
      }
    }
  },
```

The same behavior can be observed with the above.

**Comment by douglasg14b** [comment]
I can help debug if you want, I have not yet since I suspected you might have some ideas where the problem would lie given you're familiar with the code.

**Comment by RonaldJerez** [comment]
I’m still confused as to what it is that your code is trying to accomplish.

Based on your code example and my understanding of the code this is what is
happening:

Initially value is passed in, we’ll call this value A.
The directive receives this value and formats it based on the mask given,
let’s call this value B.  The input event is emitted given you value A and
value B (unmasked and masked respectively), while displaying the value B to
the user.  Your event handler now takes those values and sets the model
back to value A. Thus setting the input value back to the unmasked view and
replacing what the directive is displaying.

You cannot have the model of the input and the unmasked value be the same.
If your goal is to get the unmasked value I would recommend reassigning it
to a different variable and letting the directive handle the v-model BAU.
