### ISSUE TITLE
Pass custom tokens with a directive

### ISSUE THREAD

**Issue by hel-dev** [RonaldJerez/vue-input-facade#43]
Hello,

according to the documentation:

> The directive has all the same features as the component, however the interface may not be as straight forward

But I can't figure out how to pass custom tokens in runtime since the only directive defined seems to be the facade one.

Thank you very much and keep up the good work!

**Comment by RonaldJerez** [comment]
I though I had a example of that in the docs.

you can pass an object to the directive instead of just a string, in which you can pass some of the configs including the tokens.  The tokens will be merged with the default so you just need to supply new or updating existing tokens.

```
<input type="text" v-model="value" v-facade="{
  mask: 'XXX-###-AA',
  tokens: { 
    '#': { pattern: /[0-3]/ }
  }
}">
```

**Comment by hel-dev** [comment]
This is exactly what I was looking for!

Thank you very much @RonaldJerez!
