### ISSUE TITLE
Should document differences to vue-the-mask

### ISSUE THREAD

**Issue by MiniGod** [RonaldJerez/vue-input-facade#5]
I'm looking for an alternative to `vue-the-mask`.

It would be great to mention in the README whether this is a drop-in-replacement, or if I need to change something. You only mention that it is a fork.

As far as I can tell, the tokens are the same except the escape token?

**Comment by RonaldJerez** [comment]
It is not a drop-in replacement. Yes the tokens are the same except for the escape. But the component tag is different as well as directive name.

You can however make it more of a straight forward migration by supplying your own directive name as well as the tokens if you wish to keep the escape one the same. This is mentioned in the [demo page’s advance section](https://ronaldjerez.github.io/vue-input-facade/#advanced)
