### ISSUE TITLE
Cannot paste French IBAN with mask

### ISSUE THREAD

**Issue by ofthelit** [RonaldJerez/vue-input-facade#58]
The mask:
`FR## #### #### ##XX XXXX XXXX X##`

The pasted IBAN with different spacing:
FR 14 20041 01005 0500013M026 06
FR14 2004 1010 0505 0001 3M02 606
Copied from https://bank.codes/iban/structure/france/

The last number gets dropped after pasting in the IBAN.

Used as follows:
```
<el-input
                  :placeholder="ibanPlaceholder"
                  masked
                  v-facade="ibanMask"
                  @keyup.native="setIbanMask"
                  @blur="setIbanMask"
                  :maxlength="64"
                  v-model="formData.bankAccount.iban"></el-input>
```

Where `setIbanMask` is a function to switch to a matching iban placeholder.

**Comment by RonaldJerez** [comment]
I tried in on the demo page, not cutting off with your examples.

Have your tried your input without the additional blur or key up events?

also looks like you didn’t follow the bug report template. It’s hard for me to reproduce without knowing which device/browser/version you are having the issue on.

**Comment by ofthelit** [comment]
Thank you for your quick response. I noticed the abandoned vue-the-mask library we replaced has the same problem with the above data. This issue looks unrelated to the masking now.
