### ISSUE TITLE
Don't use npm as dependency

### ISSUE THREAD

**Issue by asicfr** [RonaldJerez/vue-input-facade#59]
Hi,
Please, can you delete npm as dependency ? 
"dependencies": {
    "npm": "^8.4.1"
}

Thanks

**Comment by RonaldJerez** [comment]
Ohhh, yes great catch, that should not be there. Must have slipped in during the deps upgrade. 

Thanks, will remove.

**Comment by RonaldJerez** [comment]
Fix in 2.0.1

**Comment by asicfr** [comment]
Thanks a lot.
