### ISSUE TITLE
Cannot set null value in v-model fields with mask array v-mask="['###.###.###-##', '##.###.### / ####-##']"

### ISSUE THREAD

**Issue by eder-ferraz-caciano** [RonaldJerez/vue-input-facade#67]
**Describe the bug**

When using a mask array in the v-mask directive, it is not possible to set a null value in the v-model. This makes it impossible to reset the form data.
Example of using the mask:
`<input
  v-model="CpfCnpj"
  type="text"
  v-mask="['###.###.###-##', '##.###.###/####-##']"
/>`
`<button @click="CpfCnpj = null">
  Clear
</button>
`

**To Reproduce**
1. Use a mask array in the mask directive as in the example: v-mask="['###.###.###-##', '##.###.###/## ##-##']"
2. set value in v-model ex: 
`<button @click="CpfCnpj = 00133266545">
  Set Value
</button>`
![image](https://user-images.githubusercontent.com/70242836/185952505-554746c0-9065-4829-9b8c-2c8fbd5e62e4.png)
4. Set a null value in the v-model of the component where the mask array is used. 
`<button @click="CpfCnpj = null">
  Clear
</button>`
6. When setting null value in v-model, it is not applied.

**Expected behavior**
It must be possible to set a null value in the v-model that has the mask array

**Desktop (please complete the following information):**
 - OS: Microsoft Windows 11 Pro - v 10.0.22000 - 22000
 - Browser [Chrome]
 - Version [v 104.0.5112.82 - 64 bits]

**Additional context**
Only the component that uses a mascara array doesn't allow to set null value in v-model. So correctly a form is impossible.

**Comment by RonaldJerez** [comment]
I was unable to reproduce this on both chrome or safari, setting to null worked fine in the demo page.

![dynamic-masks](https://user-images.githubusercontent.com/2489845/193965287-5d92385c-57ac-440f-b9ff-6183304ce621.gif)

**Comment by MatthewAry** [comment]
I am having this problem. Here is my attempt to reproduce. https://codepen.io/MatthewAry/pen/MWXOzJV

**Comment by simonmaass** [comment]
i am having the same problem with vuetify
