### ISSUE TITLE
Script 1002 Issue in IE

### ISSUE THREAD

**Issue by brianrivet** [RonaldJerez/vue-input-facade#7]
Hi,

I'm trying to use this plugin to mask some fields on a site that needs IE11 support and I'm getting a script 1002 error that says there is a syntax error. When I check out the syntax error it jumps to a line with an arrow function. It says this:

transform:e=>e.toLocalUpperCase

How would I go about resolving this?

**Comment by RonaldJerez** [comment]
@brianrivet Hi Brian,  In order to keep the script build size down I specifically exclude IE.  If you require IE support you can fork the project, modify the .browserslistrc file and rebuild.

**Comment by eduarguz** [comment]
*Unfortunately* I would love IE11 support
